### ISSUE TITLE
Komentar na opis i dijagram

### ISSUE THREAD

**Issue by IvanaTanasijevic** [leonardovlibido/pbp_RezervacijaKafica#1]
0. Opis je dobar

1. Kao sto smo juce diskutovali, predlog je da rezervacije imaju polje status ("na cekanju", "obradjena", "odbijena"). Moze i imati komentar (zasto je odbijena - nema slobodnih stolova, da li je prihvacena, da li postoji neki uslov - doci do 22h, hvala na rezervaciji u nasem kaficu... to popunjava konobar koji obradjuje rezervaciju)

2. Prilikom obrade se rezervise konkretni sto (ili stolovi, zasto da ne?)

3. Korisnik ne mora da je ocenio ni jedan kafic a moze oceniti vise kafica

4. Posaljite mi svoj email posto ga nemam u evidenciji

Pozdrav,
Ivana

**Comment by leonardovlibido** [comment]
1. Dodat status. Slazem se da komentar moze biti koristan, takodje je i to dodato u tabelu.
2. Prilikom obrade se mogu rezervisati jedan ili vise stolova, iz tog razloga je veza izmedju odobrava i bira sto jedan ili vise.
3. Procesljao sam model, i popravio nekoliko sitnica ukljucujuci i ovu.
4. E-mail je poslat.
